# Generated by Django 3.2.9 on 2022-01-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220131_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaprod',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
