# Generated by Django 3.2.9 on 2022-01-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='image',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
